version: "3.8"

services:
  redis:
    container_name: rate-limiter_redis
    image: redis:7.2.4-alpine3.19
    env_file:
      - path: ./.env
        required: true
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data
    networks:
      - default

  api:
    env_file:
      - path: ./.env
        required: true
    container_name: rate-limiter_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - default
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}

volumes:
  redis-data:

networks:
  default:
